messaging:
  sms:
    send:
      curl:
        source: '_examples/messaging/sending-an-sms/basic/cURL'
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/sms/send.js'
        from_line: 9
      java:
        source: '.repos/nexmo-community/nexmo-java-quickstart/src/main/java/com/nexmo/quickstart/sms/SendMessage.java'
        from_line: 41
        to_line: 51
        unindent: true
      csharp:
        source: '.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Controllers/SMSController.cs'
        from_line: 31
        to_line: 38
        unindent: true
      php:
        source: '.repos/nexmo-community/nexmo-php-quickstart/sms/send-sms.php'
        from_line: 9
      python:
        source: '.repos/nexmo-community/nexmo-python-quickstart/sms/__init__.py'
      ruby:
        source: '.repos/nexmo-community/nexmo-ruby-quickstart/sms/send.rb'
        from_line: 8
        to_line: 19
