library:
  initialization:
    basic:
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/initialize/basic.js'
      php:
        source: '.repos/nexmo-community/nexmo-php-quickstart/initialize/basic.php'
        from_line: 3
      java:
        source: '.repos/nexmo-community/nexmo-java-quickstart/initialize/basic.java'
    application:
      php:
        source: '.repos/nexmo-community/nexmo-php-quickstart/initialize/application.php'
        from_line: 3
    full:
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/initialize/full.js'
messaging:
  sms:
    send:
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/sms/send.js'
        from_line: 14
      java:
        source: '.repos/nexmo-community/nexmo-java-quickstart/src/main/java/com/nexmo/quickstart/sms/SendMessage.java'
        from_line: 44
        to_line: 50
        unindent: true
      csharp:
        source: '.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Controllers/SMSController.cs'
        from_line: 32
        to_line: 39
        unindent: true
      php:
        source: '.repos/nexmo-community/nexmo-php-quickstart/sms/send-sms.php'
        from_line: 5
        to_line: 16
      python:
        source: '.repos/nexmo-community/nexmo-python-quickstart/sms/__init__.py'
      ruby:
        source: '.repos/nexmo-community/nexmo-ruby-quickstart/sms/send.rb'
        from_line: 9
        to_line: 20
voice:
  outbound:
    node:
      source: '.repos/nexmo-community/nexmo-node-quickstart/voice/make-call.js'
      from_line: 20
    php:
      source: '.repos/nexmo-community/nexmo-php-quickstart/voice/text-to-speech-outbound.php'
      from_line: 12
      to_line: 22
