library:
  initialization:
    basic:
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/sms/send.js'
        from_line: 7
        to_line: 12
messaging:
  sms:
    send:
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/sms/send.js'
        from_line: 14
      java:
        source: '.repos/nexmo-community/nexmo-java-quickstart/src/main/java/com/nexmo/quickstart/sms/SendMessage.java'
        from_line: 42
        to_line: 52
        unindent: true
      csharp:
        source: '.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Controllers/SMSController.cs'
        from_line: 32
        to_line: 39
        unindent: true
      php:
        source: '.repos/nexmo-community/nexmo-php-quickstart/sms/send-sms.php'
        from_line: 6
        to_line: 14
      python:
        source: '.repos/nexmo-community/nexmo-python-quickstart/sms/__init__.py'
      ruby:
        source: '.repos/nexmo-community/nexmo-ruby-quickstart/sms/send.rb'
        from_line: 9
        to_line: 20
